<?xml version="1.0" encoding="utf-8"?><Database Name="myDB" Class="stTableDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=myDB;Integrated Security=True;Connect Timeout=30;Encrypt=False;Trust Server Certificate=False" SettingsObjectName="QLSV.Properties.Settings" SettingsPropertyName="myDBConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.std" Member="stds">
    <Type Name="std">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="fname" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="lname" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="bdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="gender" Type="System.String" DbType="NChar(6)" CanBeNull="true" />
      <Column Name="phone" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="address" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="picture" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
</Database>